server:
   port: 80
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
   type-aliases-package: com.liada.springboot.mybatis.entities # 所有Entity别名类所在包
   mapper-locations:
   - classpath:mybatis/mapper/**/*.xml # mapper映射文件
spring:
   datasource: 
      #type: com.zaxxer.hikari.HikariDataSource 
      driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
      url: jdbc:mysql://123.207.97.65/clouddb01?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true # 数据库名称
      username: root
      password: 2294625664
      dbcp2:
         min-idle: 5 # 数据库连接池的最小维持连接数
         initial-size: 5 # 初始化连接数
         max-total: 5 # 最大连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间