server:
   port: 7002
   
security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: edmin     # 用户名
    password: 123  # 密码 
       
spring: 
   application:
       name: microcloud-eureka-7002
eureka:
   instance: # eureak实例定义
      hostname: eureka-7002.com # 定义Eureka实例所在的主机名称
   client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:123@eureka-7001.com:7001/eureka,http://edmin:123@eureka-7003.com:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
    #server:
    #enable-self-preservation: true # 设置为false表示关闭保护模式
    #eviction-interval-timer-in-ms: 60000 # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）